### ISSUE TITLE
CONTRIB: browser-sync dependency scope

### ISSUE THREAD

**Issue by davorpa** [vinjatovix/a_00_apuntes#1]
Hi

First of all, a great work excluding `node_modules` from git ;)

As bootcamp colleage I want to help you with install (https://docs.npmjs.com/cli/install) scopes on NodeJS.

It is a bad practice install dev dependencies as compile dependencies. If you only use `browser-sync` to run project it is a development dependency.

https://github.com/vinjatovix/a_00_apuntes/blob/b02f3e6d9980747ee660970170bda34dcabfa259/package.json#L11-L15

Follow the official instructions to install `browser-sync` https://browsersync.io/docs#installation. Basically two options:

1. Install globally: `npm install -g browser-sync`
2. Install as development: `npm install -D browser-sync`

Before that, remember first uninstall it (https://docs.npmjs.com/cli/uninstall) to clean `package.json`.

I hope this helps you

**Comment by vinjatovix** [comment]
Hey! what's up buddy?
Glad to see you here. =)

Thank you for stopping by my repos.
This one in particular was a temp repo. 
I'm going to delete it cuz my real JS notes are in private yet.

Thank you by the way =)

I usually use nodemon instead of browser-sync.
I'm trying to figure out the advantages of one over the other and over the live server extension in vscode, live reload, etc ...
But I see that with the time window we've in the bootcamp, I will look for it on my own.

=D

Cya Pal!

**Comment by davorpa** [comment]
Hi folk

I understand you, and thus it doesn't matters. Therefore I close this ticket.

Have a good day =D
